# Generated by Django 3.0.1 on 2019-12-26 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'managed': True},
        ),
    ]
